### ISSUE TITLE
The `npm run seed` command fails

### ISSUE THREAD

**Issue by penberg** [turso-extended/api-mug-store-api#6]
```
penberg@vonneumann api-turso-cf-workers % npm run seed


> api-turso-cf-workers@0.0.1 seed
> tsx drizzle/seed

/Users/penberg/src/tursodatabase/api-turso-cf-workers/node_modules/@libsql/client/lib-cjs/hrana.js:287
        return new api_js_1.LibsqlError(e.message, code, e);
               ^

LibsqlError: SQLITE_UNKNOWN: SQLite error: no such table: categories
    at null.mapHranaError (/Users/penberg/src/tursodatabase/api-turso-cf-workers/node_modules/@libsql/client/lib-cjs/hrana.js:287:16)
    at HttpClient.execute (/Users/penberg/src/tursodatabase/api-turso-cf-workers/node_modules/@libsql/client/lib-cjs/http.js:84:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at PreparedQuery.all (/Users/penberg/src/tursodatabase/api-turso-cf-workers/node_modules/src/libsql/session.ts:223:16)
    at null.seed (/Users/penberg/src/tursodatabase/api-turso-cf-workers/drizzle/seed.ts:23:33) {
  code: 'SQLITE_UNKNOWN',
  [cause]: [ResponseError: SQLite error: no such table: categories] {
    code: 'SQLITE_UNKNOWN',
    proto: {
      message: 'SQLite error: no such table: categories',
      code: 'SQLITE_UNKNOWN'
    }
  }
}
```

**Comment by penberg** [comment]
After cleaning up the working directory, and re-doing the steps, it now works. Thanks @xinnks for the help!
